export interface Report {
  reportId: number;
  chaplain: string;
  chaplainDivision: string;
  hoursOfService?: number | null;
  commuteTime?: number | null;
  primaryAgency: string;
  secondaryAgency?: string | null;
  otherAgency?: string | null;
  typeOfService: string;
  contactName: string;
  pocPhone?: string | null;
  pocEmail?: string | null;
  clientName?: string | null;
  clientPhone?: string | null;
  addressDispatch: string;
  addressLine2Dispatch?: string | null;
  cityDispatch: string;
  stateDispatch?: string | null;
  postalCodeDispatch?: string | null;
  addressDestination?: string | null;
  cityDestination?: string | null;
  dispatchTime?: string | null;
  arrivalTime?: string | null;
  milesDriven?: number | null;
  narrative: string;
  dateDispatch?: string | null;
  dateCreated: string;
  createdById: number;
}
