# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - sopsc-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout code
        # This step checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
        # For more information, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#checkout
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "v8.0"

      - name: Build with dotnet
        run: dotnet build "Backend/SOPSC.Api/SOPSC.Api.csproj" --configuration Release

      - name: dotnet publish
        run: dotnet publish "Backend/SOPSC.Api/SOPSC.Api.csproj" -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5A28650927AD4BB281D47748A5DE6C6F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_035709EA83304216986C1EC91D22E2D7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_55E0DDAD3A8440B19CCBAEB9BC83EF98 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "sopsc-api"
          slot-name: "Production"
          package: .net-app
